apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: kube-logging
  labels:
    app: kibana-service
spec:
  selector:
    app: kibana-service
  type: NodePort
  ports:
    - name: kibana-service-port
      port: 5601
      targetPort: kibana
      protocol: TCP
