apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  name: kibana
  namespace: kube-logging
  labels:
    app: kibana
spec:
  serviceRef:
    name: kibana-service
    port: 5601
  # Put this ALB if you wanna reuse ALB
  targetGroupARN: '****'
